apiVersion: v1
kind: Service
metadata:
  name: product-management-api-service
  labels:
    app: product-management-api
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: product-management-api
